# Setup
name:         viagra's blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/blog"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
